version: 2.1

executors:
  build_container:
    working_directory: ~/workspace
    docker:
      - image: circleci/ruby:2.6.1-node

jobs:
  set_up_workspace:
    executor: build_container
    steps:
      - checkout

      - restore_cache:
          keys:
            - ruby-cache-v1-{{ checksum "Gemfile" }}
            - ruby-cache-v1

      - run:
          name: Install ruby dependencies
          command: bundle install

      - save_cache:
          key: ruby-cache-v1-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
            - vendor/cache

      - restore_cache:
          keys:
            - yarn-cache-v2-{{ checksum "yarn.lock" }}
            - yarn-cache-v2-

      - run:
          name: Install yarn dependencies
          command: yarn install

      - save_cache:
          key: yarn-cache-v2-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/
          paths:
            - workspace

  unit_tests:
    executor: build_container
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: rubocop
          command: bundle exec rubocop

      - run:
          name: rake test
          command: bundle exec rake test

  schema_check:
    executor: build_container
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Starting server
          command: bundle exec rails server
          background: true

      - run:
          name: apollo service:check
          command: sleep 5 && npx apollo service:check

      - run:
          name: apollo service:push if master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npx apollo service:push
            else
              echo "Not master, not pushing"
            fi

workflows:
  version: 2.1

  build_and_test:
    jobs:
      - set_up_workspace
      - unit_tests:
          requires:
            - set_up_workspace
      - schema_check:
          requires:
            - set_up_workspace
