development:
  adapter: postgresql
  database: graphql_ruby_development
  host: 0.0.0.0
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

test:
  adapter: postgresql
  database: graphql_ruby_test
  host: 0.0.0.0
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  adapter: postgresql
  database: graphql_ruby_production
  host: 0.0.0.0
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
